### ISSUE TITLE
jupyter_client >= 7.0.0 is not compatible with EG

### ISSUE THREAD

**Issue by abzymeinsjtu** [jupyter/enterprise_gateway#1001]
## Description

seems that jupyter_client 7.0.2 has been available by conda installation and EG 3.0.0 doesn't work with the version. better specify in `requirements.yaml` that `jupyter_client<7.0`？

## Screenshots / Logs

```
[E 210906 17:40:31 web:1789] Uncaught exception POST /api/kernels (140.205.147.65)
    HTTPServerRequest(protocol='http', host='101.37.24.61:8889', method='POST', uri='/api/kernels', version='HTTP/1.1', remote_ip='140.205.147.65')
    Traceback (most recent call last):
      File "/usr/lib/miniconda3/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/lib/miniconda3/lib/python3.8/site-packages/enterprise_gateway/services/kernels/handlers.py", line 90, in post
        await super(MainKernelHandler, self).post()
      File "/usr/lib/miniconda3/lib/python3.8/site-packages/jupyter_server/services/kernels/handlers.py", line 46, in post
        kernel_id = await km.start_kernel(kernel_name=model['name'],
      File "/usr/lib/miniconda3/lib/python3.8/site-packages/enterprise_gateway/services/kernels/remotemanager.py", line 156, in start_kernel
        kernel_id = await super(RemoteMappingKernelManager, self).start_kernel(*args, **kwargs)
      File "/usr/lib/miniconda3/lib/python3.8/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 187, in start_kernel
        kernel_id = await ensure_async(self.pinned_superclass.start_kernel(self, **kwargs))
      File "/usr/lib/miniconda3/lib/python3.8/site-packages/jupyter_server/utils.py", line 180, in ensure_async
        result = await obj
      File "/usr/lib/miniconda3/lib/python3.8/site-packages/jupyter_client/multikernelmanager.py", line 189, in _async_start_kernel
        await fut
      File "/usr/lib/miniconda3/lib/python3.8/site-packages/jupyter_client/multikernelmanager.py", line 166, in _add_kernel_when_ready
        await kernel_awaitable
      File "/usr/lib/miniconda3/lib/python3.8/site-packages/jupyter_client/utils.py", line 29, in ensure_async
        return await obj
      File "/usr/lib/miniconda3/lib/python3.8/site-packages/enterprise_gateway/services/kernels/remotemanager.py", line 365, in start_kernel
        await super(RemoteKernelManager, self).start_kernel(**kwargs)
      File "/usr/lib/miniconda3/lib/python3.8/site-packages/jupyter_client/manager.py", line 335, in _async_start_kernel
        await ensure_async(self._launch_kernel(kernel_cmd, **kw))
      File "/usr/lib/miniconda3/lib/python3.8/site-packages/jupyter_client/utils.py", line 29, in ensure_async
        return await obj
      File "/usr/lib/miniconda3/lib/python3.8/site-packages/enterprise_gateway/services/kernels/remotemanager.py", line 425, in _launch_kernel
        proxy = await self.process_proxy.launch_process(kernel_cmd, **kwargs)
      File "/usr/lib/miniconda3/lib/python3.8/site-packages/enterprise_gateway/services/processproxies/yarn.py", line 103, in launch_process
        self.local_proc = self.launch_kernel(kernel_cmd, **kwargs)
      File "/usr/lib/miniconda3/lib/python3.8/site-packages/enterprise_gateway/services/processproxies/processproxy.py", line 470, in launch_kernel
        return launch_kernel(cmd, **kwargs)
      File "/usr/lib/miniconda3/lib/python3.8/site-packages/jupyter_client/launcher.py", line 169, in launch_kernel
        raise ex
      File "/usr/lib/miniconda3/lib/python3.8/site-packages/jupyter_client/launcher.py", line 157, in launch_kernel
        proc = Popen(cmd, **kwargs)
    TypeError: __init__() got an unexpected keyword argument 'kernel_id'
```

## Environment

- Enterprise Gateway Version 3.0.0_dev
- Platform: All
- Others [jupyter_client >= 7.0.0]

**Comment by abzymeinsjtu** [comment]
another question, any plan to support >=7.0?

**Comment by kevin-bates** [comment]
Yes.  As noted in https://github.com/jupyter/enterprise_gateway/pull/983#issue-698105915, jupyter_client 7.0 introduces [_Kernel Provisioners_](https://jupyter-client.readthedocs.io/en/latest/provisioning.html) which are based on Process Proxies. 

With Kernel Provisioners, most of EG's `RemoteMappingKernelManager` and `RemoteKernelManager` implementations will go away since the same kind of abstraction is now provided by jupyter_client.
