### ISSUE TITLE
All jupyter enterprise kernels disappear if they get killed by Yarn Application Manager...

### ISSUE THREAD

**Issue by kkalugerov** [jupyter/enterprise_gateway#405]
The problem is that if I kill kernel from Yarn Application Manager then the jupyter enterprise gateway throws me this stack of exceptions : 

`[E 180731 15:37:54 web:2064] 500 DELETE /api/kernels/d406d7e6-e503-44f8-9241-aa686abbfd2d (94.130.36.32) 3225.60ms
[E 180731 15:37:54 web:1591] Uncaught exception GET /api/kernels/d406d7e6-e503-44f8-9241-aa686abbfd2d (94.130.36.32)
    HTTPServerRequest(protocol='http', host='ip-address:8888', method='GET', uri='/api/kernels/d406d7e6-e503-44f8-9241-aa686abbfd2d', version='HTTP/1.1', remote_ip='ip-address', headers={'Authorization': 'token', 'Connection': 'close', 'Host': 'ip-address:8888', 'Accept-Encoding': 'gzip'})
    Traceback (most recent call last):
      File "/home/hadoopuser/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1510, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/hadoopuser/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 2898, in wrapper
        return method(self, *args, **kwargs)
      File "/home/hadoopuser/anaconda3/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 61, in get
        model = km.kernel_model(kernel_id)
      File "/home/hadoopuser/anaconda3/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 333, in kernel_model
        "connections": self._kernel_connections[kernel_id],
    KeyError: 'd406d7e6-e503-44f8-9241-aa686abbfd2d'
[E 180731 15:37:54 web:2064] 500 GET /api/kernels/d406d7e6-e503-44f8-9241-aa686abbfd2d (94.130.36.32) 4.03ms
[W 2018-07-31 15:38:52.883 EnterpriseGatewayApp] Exception occurred sending listener shutdown to 127.0.0.1:33735 for KernelID 'd406d7e6-e503-44f8-9241-aa686abbfd2d' (using remote kill): [Errno 111] Connection refused
[W 2018-07-31 15:38:52.883 EnterpriseGatewayApp] Exception occurred attempting to shutdown communication socket to 127.0.0.1:33735 for KernelID 'd406d7e6-e503-44f8-9241-aa686abbfd2d' (ignored): [Errno 107] Transport endpoint is not connected
[E 2018-07-31 15:38:52.883 EnterpriseGatewayApp] Exception restarting kernel
    Traceback (most recent call last):
      File "/home/hadoopuser/anaconda3/lib/python3.6/site-packages/enterprise_gateway/services/processproxies/processproxy.py", line 739, in send_signal
        sock.connect((self.comm_ip, self.comm_port))
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/home/hadoopuser/anaconda3/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 85, in post
        yield gen.maybe_future(km.restart_kernel(kernel_id))
      File "/home/hadoopuser/anaconda3/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 272, in restart_kernel
        super(MappingKernelManager, self).restart_kernel(kernel_id)
      File "/home/hadoopuser/anaconda3/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 33, in wrapped
        r = method(*args, **kwargs)
      File "/home/hadoopuser/anaconda3/lib/python3.6/site-packages/enterprise_gateway/services/kernels/remotemanager.py", line 153, in restart_kernel
        super(RemoteKernelManager, self).restart_kernel(now, **kw)
      File "/home/hadoopuser/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 360, in restart_kernel
        self.shutdown_kernel(now=now, restart=True)
      File "/home/hadoopuser/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 326, in shutdown_kernel
        self.finish_shutdown()
      File "/home/hadoopuser/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 280, in finish_shutdown
        if self.is_alive():
      File "/home/hadoopuser/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 452, in is_alive
        if self.kernel.poll() is None:
      File "/home/hadoopuser/anaconda3/lib/python3.6/site-packages/enterprise_gateway/services/processproxies/processproxy.py", line 138, in poll
        return self.send_signal(0)
      File "/home/hadoopuser/anaconda3/lib/python3.6/site-packages/enterprise_gateway/services/processproxies/processproxy.py", line 746, in send_signal
        if e.errno == errno.ECONNREFUSED and signum == 0:  # Return False since there's no process.
    NameError: name 'errno' is not defined`

Any suggestions :?

**Comment by kevin-bates** [comment]
I don't see this behavior.  If I attempt to kill the yarn application from the YARN Resource Manager UI, Enterprise Gateway detects this as the kernel aborting prematurely and issues its kernel restart sequence:
```
[D 2018-08-07 06:41:56.898 EnterpriseGatewayApp] activity on c44b7cc1-21a6-4f92-975b-de7055130f81: status
[I 2018-08-07 06:42:38.600 EnterpriseGatewayApp] KernelRestarter: restarting kernel (1/5), keep random ports
[W 180807 06:42:38 handlers:466] kernel c44b7cc1-21a6-4f92-975b-de7055130f81 restarted
[D 2018-08-07 06:42:38.602 EnterpriseGatewayApp] RemoteKernelManager.signal_kernel(9)
[D 2018-08-07 06:42:38.602 EnterpriseGatewayApp] YarnClusterProcessProxy.send_signal 9
[D 2018-08-07 06:42:38.635 EnterpriseGatewayApp] YarnClusterProcessProxy.kill: kill_app_by_id(application_1532968067554_0023) response: {u'state': u'KILLED'}, confirming app state is not RUNNING
[D 2018-08-07 06:42:38.666 EnterpriseGatewayApp] Sending signal: 15 to target: -29237 on host: xxx.xxx.xxx.xxx
[D 2018-08-07 06:42:39.079 EnterpriseGatewayApp] SIGTERM signal sent to pid: 29282
[D 2018-08-07 06:42:39.111 EnterpriseGatewayApp] YarnClusterProcessProxy.kill, application ID: application_1532968067554_0023, kernel ID: c44b7cc1-21a6-4f92-975b-de7055130f81, state: KILLED
[D 2018-08-07 06:42:39.147 EnterpriseGatewayApp] Instantiating kernel 'Spark - Python (YARN Cluster Mode)' with process proxy: enterprise_gateway.services.processproxies.yarn.YarnClusterProcessProxy
[D 2018-08-07 06:42:39.149 EnterpriseGatewayApp] Response socket launched on xxx.xxx.xxx.xxx, port: 38069 using 5.0s timeout
[D 2018-08-07 06:42:39.149 EnterpriseGatewayApp] Starting kernel: [u'/usr/local/share/jupyter/kernels/spark_python_yarn_cluster/bin/run.sh', u'/home/elyra/.local/share/jupyter/runtime/kernel-c44b7cc1-21a6-4f92-975b-de7055130f81.json', u'--RemoteProcessProxy.response-address', u'xxx.xxx.xxx.xxx:38069', u'--RemoteProcessProxy.port-range', u'0..0', u'--RemoteProcessProxy.spark-context-initialization-mode', u'lazy']
```
I'm curious if the actions you took are to test a kernel's resilience or is that your understanding of how kernels should be terminated?  If the latter, you should terminate the kernel from the Notebook UI via `File/Close and Halt` or with a `DELETE` request against `/api/kernels/<kernel_id>` via the REST api.

Can you attach your complete EG log?  I see references to localhost (`127.0.0.1`) that should not be present, so I suspect there may be a configuration anomaly happening as well. The communication socket should have a cluster IP address.

**Comment by lresende** [comment]
Also, we would recommend you moving to latest EG release if you are not yet which is [0.9.4](https://github.com/jupyter-incubator/enterprise_gateway/releases/tag/v0.9.4)

**Comment by kevin-bates** [comment]
I'm going to close this issue since it's had a couple of months of inactivity.  If this issue still occurs using the current releases [1.0.2](https://github.com/jupyter/enterprise_gateway/releases/tag/v1.0.2) or [1.1.0](https://github.com/jupyter/enterprise_gateway/releases/tag/v1.1.0), then please re-open.
