### ISSUE TITLE
AttributeError: 'ResourceManager' object has no attribute 'http_conn'

### ISSUE THREAD

**Issue by 223311** [jupyter/enterprise_gateway#627]
I am getting below exception in jupyter enterprise gateway console .Please 

E 190404 08:02:55 web:1591] Uncaught exception POST /api/kernels (35.197.41.229)
    HTTPServerRequest(protocol='http', host='*****:8888', method='POST', uri='/api/kernels', version='HTTP/1.1', remote_ip='******', headers={'Content-Length': '119', 'Accept-Encoding': 'gzip', 'Connection': 'close', 'Host': '*****:8888', 'Content-Type': 'application/x-www-form-urlencoded', 'Authorization': 'Basic Z3Vlc3Q6Z3Vlc3QtcGFzc3dvcmQ='})
    Traceback (most recent call last):
      File "/opt/conda/anaconda/lib/python2.7/site-packages/tornado/web.py", line 1512, in _execute
        result = yield result
      File "/opt/conda/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/opt/conda/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "/opt/conda/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/opt/conda/anaconda/lib/python2.7/site-packages/kernel_gateway/services/kernels/handlers.py", line 71, in post
        yield super(MainKernelHandler, self).post()
      File "/opt/conda/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/opt/conda/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "/opt/conda/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/opt/conda/anaconda/lib/python2.7/site-packages/notebook/services/kernels/handlers.py", line 47, in post
        kernel_id = yield gen.maybe_future(km.start_kernel(kernel_name=model['name']))
      File "/opt/conda/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()     
 File "/opt/conda/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "/opt/conda/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/opt/conda/anaconda/lib/python2.7/site-packages/enterprise_gateway/services/kernels/remotemanager.py", line 28, in start_kernel
        kernel_id = yield gen.maybe_future(super(RemoteMappingKernelManager, self).start_kernel(*args, **kwargs))
      File "/opt/conda/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/opt/conda/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "/opt/conda/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/opt/conda/anaconda/lib/python2.7/site-packages/kernel_gateway/services/kernels/manager.py", line 81, in start_kernel
        kernel_id = yield gen.maybe_future(super(SeedingMappingKernelManager, self).start_kernel(*args, **kwargs))
      File "/opt/conda/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/opt/conda/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "/opt/conda/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 307, in wrapper
        yielded = next(result)
      File "/opt/conda/anaconda/lib/python2.7/site-packages/notebook/services/kernels/kernelmanager.py", line 148, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/opt/conda/anaconda/lib/python2.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/opt/conda/anaconda/lib/python2.7/site-packages/enterprise_gateway/services/kernels/remotemanager.py", line 100, in start_kernel
        return super(RemoteKernelManager, self).start_kernel(**kw)
      File "/opt/conda/anaconda/lib/python2.7/site-packages/jupyter_client/manager.py", line 258, in start_kernel
        **kw)
      File "/opt/conda/anaconda/lib/python2.7/site-packages/enterprise_gateway/services/kernels/remotemanager.py", line 129, in _launch_kernel
        return self.process_proxy.launch_process(kernel_cmd, **kw)
      File "/opt/conda/anaconda/lib/python2.7/site-packages/enterprise_gateway/services/processproxies/yarn.py", line 55, in launch_process
        self.confirm_remote_startup(kernel_cmd, **kw)
      File "/opt/conda/anaconda/lib/python2.7/site-packages/enterprise_gateway/services/processproxies/yarn.py", line 152, in confirm_remote_startup
        if self.get_application_id(True):
      File "/opt/conda/anaconda/lib/python2.7/site-packages/enterprise_gateway/services/processproxies/yarn.py", line 208, in get_application_id
        app = self.query_app_by_name(self.kernel_id)
      File "/opt/conda/anaconda/lib/python2.7/site-packages/enterprise_gateway/services/processproxies/yarn.py", line 258, in query_app_by_name
        self.resource_mgr.http_conn.close()
    AttributeError: 'ResourceManager' object has no attribute 'http_conn'

Please suggest..

**Comment by 223311** [comment]
Please suggest..

**Comment by kevin-bates** [comment]
You should upgrade your Enterprise Gateway to >= 1.1.0 (1.2.0 recommended) or downgrade yarn-api-client < 0.3.0.

**Comment by kevin-bates** [comment]
This is very likely due to the version levels (newer yarn-api-client) that older EG didn't cap.  Closing.  Please re-open if you find otherwise.
