### ISSUE TITLE
Unable to start jupyter enterprisegateway notebook_http mode

### ISSUE THREAD

**Issue by rodolfo-flores-tierconnect-com** [jupyter/enterprise_gateway#667]
Having problems trying to start enterprisegateway in a notebook_http mode, not sure what is the problem as websocket mode is starting without errors.

jupyter enterprisegateway version: 1.2.0
jupyter version: 4.4.0
jupyter-kernel --version: 5.2.4
env with: python 3

Traceback (most recent call last):
  File "/home/mojix/anaconda3/bin/jupyter-enterprisegateway", line 10, in <module>
    sys.exit(launch_instance())
  File "/home/mojix/anaconda3/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/mojix/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "/home/mojix/anaconda3/lib/python3.7/site-packages/kernel_gateway/gatewayapp.py", line 381, in initialize
    self.init_configurables()
  File "/home/mojix/anaconda3/lib/python3.7/site-packages/enterprise_gateway/enterprisegatewayapp.py", line 246, in init_configurables
    self.personality = func(parent=self, log=self.log)
  File "/home/mojix/anaconda3/lib/python3.7/site-packages/kernel_gateway/notebook_http/__init__.py", line 157, in create_personality
    return NotebookHTTPPersonality(*args, **kwargs)
  File "/home/mojix/anaconda3/lib/python3.7/site-packages/kernel_gateway/notebook_http/__init__.py", line 66, in __init__
    kernel_language = self.parent.seed_notebook['metadata']['language_info']['name']
TypeError: 'NoneType' object is not subscriptable

I'm starting the service as the follow:
jupyter enterprisegateway --ip=0.0.0.0 --port=8999 --api='kernel_gateway.notebook_http' seed_uri='./Notebooks/microservices.ipynb'

Thanks in advance

**Comment by kevin-bates** [comment]
To be honest, I don't think anyone has spent time figuring out what is necessary to support the HTTPPersonality - as this single-kernel configuration is not within the design scope of Enterprise Gateway.  I haven't looked into what would be necessary to add this support.  As a result, users wishing to use HTTPPersonality will need to use Jupyter Kernel Gateway.
