### ISSUE TITLE
generate-config on ppc64le fails with latest anacoda openssl 1.1.1d

### ISSUE THREAD

**Issue by stevehaertel** [jupyter/enterprise_gateway#736]
Anaconda openssl is up to 1.1.1d, which breaks JEG 2.0.0 generate-config (and maybe other things!)

This problem does not happen with openssl 1.1.1c.

## Description

```
user@host:~$ /tmp/minip/anaconda/envs/env/bin/jupyter-enterprisegateway --generate-config
Traceback (most recent call last):
  File "/tmp/minip/anaconda/envs/env/bin/jupyter-enterprisegateway", line 6, in <module>
    from enterprise_gateway import launch_instance
  File "/tmp/minip/anaconda/envs/env/lib/python3.7/site-packages/enterprise_gateway/__init__.py", line 4, in <module>
    from .enterprisegatewayapp import launch_instance
  File "/tmp/minip/anaconda/envs/env/lib/python3.7/site-packages/enterprise_gateway/enterprisegatewayapp.py", line 19, in <module>
    from notebook.services.kernels.kernelmanager import MappingKernelManager
  File "/tmp/minip/anaconda/envs/env/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 15, in <module>
    from tornado import gen, web
  File "/tmp/minip/anaconda/envs/env/lib/python3.7/site-packages/tornado/web.py", line 87, in <module>
    from tornado.httpserver import HTTPServer
  File "/tmp/minip/anaconda/envs/env/lib/python3.7/site-packages/tornado/httpserver.py", line 32, in <module>
    from tornado.http1connection import HTTP1ServerConnection, HTTP1ConnectionParameters
  File "/tmp/minip/anaconda/envs/env/lib/python3.7/site-packages/tornado/http1connection.py", line 34, in <module>
    from tornado import iostream
  File "/tmp/minip/anaconda/envs/env/lib/python3.7/site-packages/tornado/iostream.py", line 40, in <module>
    from tornado.netutil import ssl_wrap_socket, _client_ssl_defaults, _server_ssl_defaults
  File "/tmp/minip/anaconda/envs/env/lib/python3.7/site-packages/tornado/netutil.py", line 39, in <module>
    _client_ssl_defaults = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
  File "/tmp/minip/anaconda/envs/env/lib/python3.7/ssl.py", line 565, in create_default_context
    context = SSLContext(PROTOCOL_TLS)
  File "/tmp/minip/anaconda/envs/env/lib/python3.7/ssl.py", line 388, in __new__
    self = _SSLContext.__new__(cls, protocol)
ssl.SSLError: [SSL] malloc failure (_ssl.c:2994)

```
## Environment

- JEG 2.0.0
- ppc64le

**Comment by stevehaertel** [comment]
I should add that the reason why openssl 1.1.1d is installed in the first place is because it's automatically updated from 1.1.1c when you install "libsodium", which is also required by the generate-config.

**Comment by kevin-bates** [comment]
Thanks @stevehaertel - do you know if this is an issue for Notebook as well?  I suspect it would be since it should be going through the same codepath from here: 
```
File "/tmp/minip/anaconda/envs/env/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 15, in <module>
    from tornado import gen, web
```
That would be a good data-point nonetheless.  I'm sorry, but I don't have access to a `ppc64le` system.

**Comment by stevehaertel** [comment]
Hmm I'm not sure, as the only time I ever set up a notebook is through an automated setup that uses this JEG too, however I can see that this 1.1.1d has caused many problems as can be seen here:
[https://github.com/ContinuumIO/anaconda-issues/issues/11274](https://github.com/ContinuumIO/anaconda-issues/issues/11274)

So this fix for this MIGHT end up being on the Anaconda side?

**Comment by stevehaertel** [comment]
@kevin-bates Actually, wait a minute -- it's really trivial for me to just run the same generate config for notebook as well...

user@host:/tmp/stp/Jupyter-5.4.0$ /tmp/minip/anaconda/envs/env/bin/jupyter notebook --generate-config
Traceback (most recent call last):
  File "/tmp/minip/anaconda/envs/env/bin/jupyter-notebook", line 6, in <module>
    from notebook.notebookapp import main
  File "/tmp/minip/anaconda/envs/env/lib/python3.7/site-packages/notebook/notebookapp.py", line 62, in <module>
    from tornado import httpserver
  File "/tmp/minip/anaconda/envs/env/lib/python3.7/site-packages/tornado/httpserver.py", line 32, in <module>
    from tornado.http1connection import HTTP1ServerConnection, HTTP1ConnectionParameters
  File "/tmp/minip/anaconda/envs/env/lib/python3.7/site-packages/tornado/http1connection.py", line 34, in <module>
    from tornado import iostream
  File "/tmp/minip/anaconda/envs/env/lib/python3.7/site-packages/tornado/iostream.py", line 40, in <module>
    from tornado.netutil import ssl_wrap_socket, _client_ssl_defaults, _server_ssl_defaults
  File "/tmp/minip/anaconda/envs/env/lib/python3.7/site-packages/tornado/netutil.py", line 39, in <module>
    _client_ssl_defaults = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
  File "/tmp/minip/anaconda/envs/env/lib/python3.7/ssl.py", line 565, in create_default_context
    context = SSLContext(PROTOCOL_TLS)
  File "/tmp/minip/anaconda/envs/env/lib/python3.7/ssl.py", line 388, in __new__
    self = _SSLContext.__new__(cls, protocol)
ssl.SSLError: [SSL] malloc failure (_ssl.c:2994)

**Comment by stevehaertel** [comment]
(Also, please ignore my directory name having "5.4.0" in it - I'm actually using the latest notebook pkg.)

**Comment by kevin-bates** [comment]
Thanks @stevehaertel - I'm inclined to let things play out in openssl-land a bit, especially since this is so many levels removed from jupyter code.  Not sure what else we can do since you imply there isn't really a workaround.

**Comment by stevehaertel** [comment]
@kevin-bates I'll close this here because I agree with your assessment, though I do still think it was a good issue to raise and bring up anyways. 

Also, the workaround is to keep openssl 1.1.1c instead of upgrading it to d, but the frustrating part is unless you know that that's the problem, it'll just look like everything is wrecked.

For example, now Jupyter/JEG wont work if you install miniconda, since it doesn't have libsodium in it, which is required by that generate-config. If you go do a conda package install of libsodium, it automatically boosts you to openssl 111d unless you pin it to use 111c. 

Definitely it's possible to do that, but we have this ridiculous extra step required, and also you have to _know_ that you have to do that, which I think a lot of people are going to have trouble with.
