### ISSUE TITLE
is it possible to use the enterprise_gateway with other CRI than docker, We would like to use containerd

### ISSUE THREAD

**Issue by dummys** [jupyter/enterprise_gateway#916]
Hi, 

Do you plan to support it ?

**Comment by kevin-bates** [comment]
If there's work to do and it doesn't "just work", then this will likely need to come from a community contribution.  Are you in a position to try this out and at least get an idea of the level of effort that would be involved in adding this support?  I would be happy to steer you in the appropriate directions should changes be necessary internally.

**Comment by Tim1000V** [comment]
@dummys I guess you are talking about the kernel image puller for k8s. 
By the way kubernetes will deprecate docker (https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/).
I managed to implement a support for containerd you can check it out on https://github.com/Tim1000V/kernel-image-puller.
Actually it is based on the v2.0.0 but the modifications shouldn't be hard to port for the latest version.
On the entreprise gateway itself there isn't any change to be made, as far as i know the gateway only uses the k8s python API which doesn't interact directly with docker or any CRI.

**Comment by Tim1000V** [comment]
Hi @kevin-bates , I can definitely do that. I will cleanup a little bit my code. And according to [https://pypi.org/project/container-runtime-interface-api/](url) this should be also compatible with cri-o (which I need to test).

**Comment by dummys** [comment]
@Tim1000V do you solve this error from the kernel puller ?

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
ConnectionRefusedError: [Errno 111] Connection refused

```

**Comment by Tim1000V** [comment]
@dummys by default the kernel image puller uses docker api to pull images and try to connect to /var/run/docker.sock (which doesn't exists). I think that why you have connection refused.
For the build I made a typo in the Dockerfile FROM elyra/kernel-**imager**-puller:2.0.0 > FROM elyra/kernel-image-puller:2.0.0

**Comment by dummys** [comment]
@Tim1000V ohh you are right, now its working. Is it possible to use it without uploading to a registry ? But rather building it locally and using it ?

**Comment by Tim1000V** [comment]
I think you will have to follow those steps https://github.com/kubernetes-sigs/cri-tools/issues/546#issuecomment-646909445. You should try to save the image like this ```buildah push imageID oci-archive:/path/to/archive:image:tag``` ([ref](https://github.com/containers/buildah/blob/master/docs/buildah-push.mdhttps://github.com/containers/buildah/blob/master/docs/buildah-push.md))
I'm working under CentOS so check where containerd.sock actually is for ubuntu (```ss -xan | grep containerd.sock```).
I can't help you for the helm part, because I'm using enterprise-gateway.yaml to (re)deploy the app.

**Comment by dummys** [comment]
ok I made it available in k8s, but I don't know how to use it, I tried elyra/kernel-image-puller-mod:latest but k8s tried to take it from docker.io. Is there a way to tell it to take it from local cri ?

**Comment by dummys** [comment]
still trying to use the local image but without luck, it is uploaded and listen correctly using `ctr``, but when deploying I get:

```
 failed to "StartContainer" for "kernel-image-puller" with ErrImageNeverPull: "Container image \"kernel-image-puller-mod:1.0\" is not present with pull policy of Never"
```

**Comment by kevin-bates** [comment]
Strange.  Did you modify KIP's [`imagePullPolicy`](https://github.com/jupyter/enterprise_gateway/blob/master/etc/kubernetes/helm/enterprise-gateway/values.yaml#L78) in the helm chart to be `Never`?

**Comment by dummys** [comment]
Yes i've done it. But it still can't find my custom image. Dunno why.

**Comment by dummys** [comment]
I have a weird issue with some command see:

`sudo crictl images`:

```
IMAGE                                                    TAG                                          IMAGE ID            SIZE
docker.io/calico/cni                                     v3.17.1                                      29b6bcc4a8b41       44.1MB
docker.io/calico/kube-controllers                        v3.17.1                                      278f40d9f3b82       22MB
docker.io/calico/node                                    v3.17.1                                      183b53858d7da       58.4MB
docker.io/calico/pod2daemon-flexvol                      v3.17.1                                      740bdc760424a       9.33MB
docker.io/elyra/enterprise-gateway                       2.3.0                                        234078a85627a       1.79GB
docker.io/elyra/enterprise-gateway                       2.4.0                                        c6f332e1508f3       1.79GB
docker.io/elyra/kernel-image-puller                      2.3.0                                        60dde9f91f88c       342MB
docker.io/grafana/grafana                                7.2.1                                        2f17bd84b75d4       59.3MB
docker.io/jettech/kube-webhook-certgen                   v1.5.0                                       344297e197b67       16.3MB
docker.io/kiwigrid/k8s-sidecar                           1.1.0                                        f4bb3bf1ddc7b       26.3MB
docker.io/kubernetesui/dashboard                         v2.1.0                                       9a07b5b4bfac0       68MB
docker.io/library/kernel-image-puller-mod                1.0                                          86644e468ab57       359MB
docker.io/library/kernel-image-puller-mod                latest                                       bac41fac5003e       359MB
docker.io/library/traefik                                2.3.3                                        353c5f5e1247e       28.4MB
docker.io/metallb/controller                             v0.9.5                                       bc16d3d985ea9       31.3MB
docker.io/metallb/speaker                                v0.9.5                                       c60accc5746b9       35.6MB
docker.io/nvidia/samples                                 dcgmproftester-2.0.10-cuda11.0-ubuntu18.04   3a72e8e920293       231MB
k8s.gcr.io/coredns                                       1.7.0                                        bfe3a36ebd252       14MB
k8s.gcr.io/etcd                                          3.4.13-0                                     0369cf4303ffd       86.7MB
k8s.gcr.io/kube-apiserver                                v1.19.5                                      72efb76839e7f       29.7MB
k8s.gcr.io/kube-apiserver                                v1.20.0                                      ca9843d3b5454       30.4MB
k8s.gcr.io/kube-controller-manager                       v1.19.5                                      f196e958af67e       28MB
k8s.gcr.io/kube-controller-manager                       v1.20.0                                      b9fa1895dcaa6       29.4MB
k8s.gcr.io/kube-proxy                                    v1.19.5                                      6e5666d85a314       49.3MB
k8s.gcr.io/kube-proxy                                    v1.20.0                                      10cc881966cfd       49.5MB
k8s.gcr.io/kube-scheduler                                v1.19.5                                      350a602e53109       13.8MB
k8s.gcr.io/kube-scheduler                                v1.20.0                                      3138b6e3d4712       14MB
k8s.gcr.io/pause                                         3.2                                          80d28bedfe5de       300kB
nvcr.io/nvidia/driver                                    450.80.02-ubuntu18.04                        62f8c7903995a       384MB
nvcr.io/nvidia/gpu-feature-discovery                     v0.2.2                                       ac5a5865991a1       90MB
nvcr.io/nvidia/gpu-operator                              1.4.0                                        3cfbe605d9bad       106MB
nvcr.io/nvidia/k8s-device-plugin                         v0.7.1                                       8e435580abbda       67MB
nvcr.io/nvidia/k8s/container-toolkit                     1.4.0-ubuntu18.04                            b13fa30548397       91.3MB
nvcr.io/nvidia/k8s/cuda-sample                           vectoradd-cuda10.2                           9ef6a0a863826       43.7MB
nvcr.io/nvidia/k8s/dcgm-exporter                         2.0.13-2.1.2-ubuntu20.04                     3526d719833de       242MB
quay.io/coreos/kube-state-metrics                        v1.9.7                                       6497f02dbdad7       10.3MB
quay.io/kubernetes_incubator/nfs-provisioner             latest                                       3830c0da69e19       90.4MB
quay.io/kubernetes_incubator/node-feature-discovery      v0.6.0                                       b7f4ca5c9efca       35.3MB
quay.io/prometheus-operator/prometheus-config-reloader   v0.44.0                                      73bc771f8028b       5.38MB
quay.io/prometheus-operator/prometheus-operator          v0.44.0                                      f5ab8d7a1a64c       13.6MB
quay.io/prometheus/alertmanager                          v0.21.0                                      c876f5897d7b0       27.1MB
quay.io/prometheus/node-exporter                         v1.0.1                                       0e0218889c33b       13MB
quay.io/prometheus/prometheus                            v2.22.1
```

There isn't my custom image but I added it using: sudo ctr -n k8s.io -a /run/containerd/containerd.sock import --base-name kernel-image-puller-mod kernel-image-puller-mod.tar`

And listing using ` sudo ctr -n k8s.io -a /run/containerd/containerd.sock images ls
`:

```
kernel-image-puller-mod:1.0                                                                                                    application/vnd.oci.image.manifest.v1+json                sha256:75656200c77d3cece90d4ac09b4f4f6822b502d688f4b87366c3487222d4bf6e 342.5 MiB linux/amd64                                                    io.cri-containerd.image=managed
```

It's there so why crictl images didn't see it ?

**Comment by dummys** [comment]
and Yes indeed it works now !

```
Collecting container-runtime-interface-api
  Downloading container_runtime_interface_api-0.0.5-py3-none-any.whl (38 kB)
Collecting grpcio~=1.30.0
  Downloading grpcio-1.30.0.tar.gz (19.7 MB)
Collecting protobuf~=3.12.2
  Downloading protobuf-3.12.4-py2.py3-none-any.whl (443 kB)
Requirement already satisfied: six>=1.5.2 in /usr/local/lib/python3.9/site-packages (from grpcio~=1.30.0->container-runtime-interface-api) (1.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (from protobuf~=3.12.2->container-runtime-interface-api) (50.3.2)
Building wheels for collected packages: grpcio
  Building wheel for grpcio (setup.py): started
```
Is there a way to control that my kernel puller is successfully pulling kernel image ?

I made a small patch to the helm stuff here:

containerd.patch
```
--- enterprise-gateway/templates/daemonset.yaml 2020-11-26 18:46:12.000000000 +0100
+++ enterprise-gateway_working/templates/daemonset.yaml 2020-12-22 15:48:03.800370573 +0100
@@ -29,11 +29,16 @@
           value: !!str {{ .Values.kip.interval }}
         - name: KIP_PULL_POLICY
           value: {{ .Values.kip.pullPolicy }}
+        - name: KIP_CRI_CLI
+          value: "Yes"
+        - name: KIP_CRI_SOCK
+          value: {{ .Values.kip.criSock }}
         volumeMounts:
-        - name: dockersock
-          mountPath: "/var/run/docker.sock"
+        - name: {{ .Values.kip.volumeName }}
+          mountPath: {{ .Values.kip.volumeMountPath }}
       volumes:
-      - name: dockersock
+      - name: {{ .Values.kip.volumeName }}
         hostPath:
-          path: /var/run/docker.sock
+          path: {{ .Values.kip.volumeHostPath }}
+
 {{- end }}
diff -ruN enterprise-gateway/values.yaml enterprise-gateway_working/values.yaml
--- enterprise-gateway/values.yaml      2020-11-26 18:46:13.000000000 +0100
+++ enterprise-gateway_working/values.yaml      2020-12-23 11:29:34.284484553 +0100
@@ -73,12 +73,23 @@
 kip:
   enabled: true
   # Kernel Image Puller image name and tag to use.
-  image: elyra/kernel-image-puller:2.4.0
+  image: localhost/kernel-image-puller-mod:1.0
   # Kernel Image Puller image pull policy.
-  imagePullPolicy: IfNotPresent
+  imagePullPolicy: Never
   # Determines whether the Kernel Image Puller will pull kernel images it has previously pulled
   pullPolicy: IfNotPresent
   # The interval (in seconds) at which the Kernel Image Puller fetches kernelspecs to pull kernel images.
   interval: 300
+  # Choose which runtime to use, example are given for docker and containerd but should works with CRI-O too only one should be uncommented
+
+  # docker
+  #criSock: "unix:///var/run/docker.sock"
+  #volumeName: dockersock
+  #volumeMountPath: "/var/run/docker.sock"
+  #volumeHostPath: /var/run/docker.sock

-
+  # containerd
+  criSock: "unix:///run/containerd/containerd.sock"
+  volumeName: containerdsock
+  volumeMountPath: "/run/containerd/containerd.sock"
+  volumeHostPath:  /run/containerd/containerd.sock
```

**Comment by kevin-bates** [comment]
This is great news @dummys!  I'm hoping a pull request can come out of this effort.  I would suggest @Tim1000V produce the PR and perhaps any further collaboration can occur to tie up any loose ends.  Thank you!!

> Working now, I had to add localhost/kernel-image-puller-mod to made it available to crictl. We can't use another base name

How did you make the KIP image available to `crtctl`?  (Sorry, this is completely foreign to me.)
What is meant by "We can't use another base name"?

> Is there a way to control that my kernel puller is successfully pulling kernel image ?

KIP's pod log will contain information on whether an image was pulled or found to already exist.  You should be able to remove an image from a respective node and see KIP replace it if you already have all the images.

Once a PR is available, I should be able to check things relative to the docker-based runtime (I'm on vacation through Jan 3, 2021 and bandwidth will be limited following).

**Comment by dummys** [comment]
> How did you make the KIP image available to `crtctl`? (Sorry, this is completely foreign to me.)
> What is meant by "We can't use another base name"?
So using whatever client you want ( I use buildah) just dump the image as `.tar` file and import it to the cluster (here im using a 1 node cluster, it's really for debug) with :

`sudo ctr -n k8s.io images import --base-name localhost/kernel-image-puller-mod kernel-image-puller-mod.tar`

Don't forget the `localhost` and the namespace `k8s.io` otherwise it will not be available to k8s.

Then to use it inside the helm chart I just dowloaded the chart and modified the values.yaml with:
PS: I'm using helm just to track the installation on my cluster, but it should be the same without helm.

```yaml
# Kernel Image Puller (daemonset)
kip:
  enabled: true
  # Kernel Image Puller image name and tag to use.
  image: localhost/kernel-image-puller-mod:1.0
```

**Comment by kevin-bates** [comment]
PR #1007 adds `crictl` to the kernel image puller and has been tested on `containerd`-based systems.  As a result, I'm going ahead with this closure.
