### ISSUE TITLE
Error when using sample R image on Enterprise Gateway

### ISSUE THREAD

**Issue by camer314** [jupyter/enterprise_gateway#955]
I followed the tutorial to setup Enterprise Gateway under Kubernetes and starting Python notebooks using the supplied 
**python_kubernetes** package works fine. However when trying to instantiate a **R_kubernetes** kernel I get the following error in the pod log

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/bin/kernel-launchers/R/scripts/gateway_listener.py", line 9, in <module>
    from Cryptodome.Cipher import PKCS1_v1_5, AES
**ModuleNotFoundError: No module named 'Cryptodome'**

This manifests as an error in the gateway log as:

[D 2021-04-22 10:19:53.280 EnterpriseGatewayApp] Waiting for KernelID '2ee05292-5b8f-48b2-902e-3b1630542ea2' to send connection info from host 'jovyan-2ee05292-5b8f-48b2-902e-3b1630542ea2' - retrying...

And finally an error in the notebook of 'Failed to fetch'

Interestingly, in the Chrome debugger its then returning as a CORS issue, which is weird. And irrelevant.

**Comment by kevin-bates** [comment]
This is not reproducible in 2.5.2 - closing (and verified during 2.6.0 preparation).
